name: Run tests

on:
    push:
    pull_request:
        branches:
        - main

jobs:
    checkout_repo:
      name: "checkout repo"
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v2
    test_go:
      name: "test go"
      runs-on: ubuntu-latest
      needs: checkout_repo
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v2

        - name: Set up Go
          uses: actions/setup-go@v2
          with:
            go-version: 1.19  # Replace with your desired Go version
  
        - name: Run Tests
          run: go test ./...
          working-directory: ./go

    test_node:
      name: "test node"
      runs-on: ubuntu-latest
      needs: checkout_repo
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v2
          
        - name: Install dependencies
          run: npm install
          working-directory: ./js/exercises

        - name: Run tests
          run: npm test
          working-directory: ./js/exercises

      